### ISSUE TITLE
xpath or children

### ISSUE THREAD

**Issue by mbojan** [ropensci/oai#11]
Is there a reason why `while_oai` and other functions use nested `xml_children` calls to extract various elements from the result (like `resumptionToken`, errors, etc.)? I think the OAI-PMH specification does not specify the order of the tags so different services might return these in different order. Using XPath seems simpler.

One trouble with XPath is handling namespaces. This might be dodged with `local-name()` like here http://stackoverflow.com/questions/16717211/getting-elements-with-default-namespace-no-namespace-prefix-using-xpath

**Comment by sckott** [comment]
@mbojan no reason. plz do go with xpath, looks like you already are doing that in your branch

**Comment by mbojan** [comment]
I think this can be closed. I used xpath in new code, but perhaps it does not make sense to modify existing code that uses `xml_children` if it works...

**Comment by sckott** [comment]
I'll at least try with other fxns
