### ISSUE TITLE
`handle_errors` test file are misbehaving

### ISSUE THREAD

**Issue by sckott** [ropensci/oai#52]
@mbojan I can't figure out why they are not working. haven't thought about it too hard yet, but I imagine you can figure it out faster. 

ive commented those tests out for now.

**Comment by mbojan** [comment]
OK, I'll have a look.

**Comment by sckott** [comment]
thanks

**Comment by mbojan** [comment]
Hmm... All `handle-errors` tests work fine for me locally now. Maybe this was some one-time service or networking problems?

**Comment by sckott** [comment]
seeing what happens on travis

**Comment by sckott** [comment]
hmm, yeah, seems to work, will uncomment those tests.

**Comment by sckott** [comment]
back to what it was in 03f50962d3a5e42f4a3efece470251bf1c6b56dc
