### ISSUE TITLE
function 'check_as' is missing

### ISSUE THREAD

**Issue by patperu** [ropensci/oai#55]
Hi Scott,
the last commit added a call for `check_as` 
https://github.com/ropensci/oai/blob/39102ff4c8ebd08cbe9ac836976bd70e7769c47b/R/id.R#L24 but the function is missing.

Maybe something like this? 

```r
# check as ----------------------------------------
check_as <- function(as) {
  if (!as %in% c('parsed', 'raw')) {
    stop(sprintf("'%s' not in acceptable set: parsed, raw", as) ,
         call. = FALSE)
  }
}
```
:wave: Patrick

**Comment by sckott** [comment]
thanks @patperu ! Sorry about that, I have some unpushed changes locally, i'll push those today and see if this is sorted out. - that's pretty darn close to what i have

**Comment by sckott** [comment]
okay, pushed up
