### ISSUE TITLE
change maintainer on cran

### ISSUE THREAD

**Issue by sckott** [ropensci/oai#67]
@mbojan  when you get a chance, could you submit a new version to cran changing the maintainer to you? not urgent, but any correspondence from cran will go to me right now, so it'd be good to have it go to you instead. thanks!

**Comment by mbojan** [comment]
True. I intended to do that but got swamped by other things... Will take care of that, @sckott

**Comment by sckott** [comment]
thanks!

**Comment by mbojan** [comment]
Submitted. I'm sure CRAN will get in touch with @sckott to confirm maintainer change.

**Comment by sckott** [comment]
Thanks! Just replied saying yes to the confirmation

**Comment by mbojan** [comment]
Updated version on CRAN.

**Comment by sckott** [comment]
great, thanks!
